python src/main.py \
    --output_dir "./experiments" \
    --comment "classification from Scratch" \
    --name EthanolConcentration \
    --records_file Classification_records.xls \
    --data_dir '/data1/guohang/dataset/Timedataset/EthanolConcentration' \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 50 \
    --lr 0.005 \
    --patch_size 8 \
    --stride 8 \
    --optimizer RAdam \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy